/// Flutter icons NapoleonIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NapoleonIcons
///      fonts:
///       - asset: fonts/NapoleonIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NapoleonIcons {
  NapoleonIcons._();

  static const _kFontFam = 'NapoleonIcons';
  static const _kFontPkg = null;

  static const IconData browser = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData task = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
